# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'testapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testapp

# pod 'FBSDKLoginKit', '~> 13.1.0'

end
